paths-ignore:
- '**/Token/**'
- '**/github-credentials.yml'

<!--- same tokens are present in application.dev.properties and secret scanning only shows this one because With the help of above
code we can exclude directory so that secret cannot scan the directory/file present in given paths. --->
